# config/sidekiq.yml
# Basic Sidekiq config — concurrency and queue definitions.
:concurrency: 5

:queues:
  - [default, 1]
  - [mailers, 2]
  - [critical, 3]

:timeout: 8
:pidfile: tmp/pids/sidekiq.pid
